---
checks:
  method-lines:
    config:
      threshold: 30
  argument-count:
    enabled: false
plugins:
  duplication:
    enabled: true
    checks:
      Similar Code:
        enabled: false
    config:
      languages:
        javascript:
          mass_threshold: 60
  eslint:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- test/
- node_modules/
- coverage/
- frontend/
